# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Winicius B. Faquieri
title: Ciência de Dados | Engenharia de ML
email: wfaquieri@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  wfaquieri
linkedin_username: wfaquieri

# About Section
about_title: Resumo
about_profile_image: images/photo_2025-11-07_10-58-16.jpg
about_content: |
  Graduado em Economia pela Universidade do Estado do Rio de Janeiro (UERJ, 2014), com mestrado em Finanças Quantitativas e Análise de Risco pela mesma instituição (2017) e pós-graduação em Inteligência Artificial, Machine Learning e Deep Learning pelo Instituto INFNET (2023).

  Ao longo dos últimos sete anos, venho solucionando desafios complexos de negócio por meio de abordagens analíticas avançadas, aliando rigor estatístico, visão estratégica e domínio técnico. Contribuí para projetos em organizações de destaque como SulAmérica, FGV e Red Asset, e atualmente atuo como Líder de Ciência de Dados na Macroplan Analytics, onde desenvolvo soluções orientadas por dados e geração de insights estratégicos.

  Sou movido pelo aprendizado contínuo e pela busca constante por inovação, mantendo-me atualizado com os avanços mais recentes em Ciência de Dados e Inteligência Artificial.

  **Soft skills:** empatia, adaptabilidade e atitude positiva.

content:  
  - title: Experiência Profissional 
    layout: list 
    content:
    
      - layout: left
        border: weak
        title: Macroplan Analytics
        link: https://www.analytics.macroplan.com.br/
        link_text: https://www.analytics.macroplan.com.br/
        sub_title: Líder Pleno em Ciência de Dados
        caption: Novembro 2024 - Atual
        description: |           
          - Liderança técnica da equipe, promovendo capacitação e boas práticas em ciência de dados e engenharia de dados;
          - Coordenação de projetos estratégicos de Data Analytics, garantindo a entrega de soluções eficazes e escaláveis;
          - Desenvolvimento e otimização de procedures SQL e Teradata, assegurando o cálculo preciso de indicadores e a melhoria do desempenho do banco de dados;
          - Projeto e implementação de pipelines de ETL com Python e Apache Airflow, automatizando o processamento de dados armazenados no Azure Blob Storage e carregando indicadores no MongoDB;
          - Aplicação de Apache Spark para o processamento de grandes volumes de dados, modelagem preditiva e implementação de algoritmos de machine learning, com rastreamento e gestão de experimentos via MLflow;
          - Implementação e gerenciamento da containerização de aplicações com Docker, garantindo portabilidade, consistência e facilidade de implantação em diferentes ambientes.
      - layout: left
        border: weak
        title: Red Asset
        link: https://redasset.com.br/
        link_text: https://redasset.com.br/
        sub_title: Cientista de Dados Pleno
        caption: Junho 2023 - Fev. 2024
        description: | 
          Na Red, fui responsável por desenvolver análises e relatórios que apoiavam as áreas de negócios, impactando as decisões operacionais e estratégicas. Desenvolvi dashboards em <mark>Shiny</mark> para visualização de dados em tempo real e monitoramento contínuo de modelos de <mark>Machine Learning</mark> em produção, alinhados às práticas de <mark>MLOps</mark>.

          Estudei e apliquei ferramentas de monitoramento para garantir a qualidade dos dados e a observabilidade dos modelos. Também otimizei e mantive dashboards interativos em <mark>R</mark> e <mark>Shiny</mark>, contribuindo para a visualização de KPIs e a tomada de decisões.

          Participei da implementação de modelos de <mark>Machine Learning</mark> em produção, utlizando a linguagem <mark>Python</mark> e bibliotecas como <mark>Scikit-learn</mark>, <mark>LightGBM</mark>, <mark>XGBoost</mark>, <mark>FastAPI</mark> e <mark>Plumber</mark>. Também colaborei na otimização de consultas <mark>SQL</mark>, melhorando a eficiência das análises de dados.
        
      - layout: left
        border: weak
        title: FGV IBRE
        link: https://portalibre.fgv.br/
        link_text: https://portalibre.fgv.br/
        sub_title: Cientista de Dados 
        caption: Maio 2019 - Maio. 2023
        description: | 
          No IBRE, realizei análises de dados utilizando as linguagens <mark>R</mark>, <mark>Python</mark> e <mark>SQL</mark> para gerar insights significativos. Desenvolvi e implementei modelos de <mark>Machine Learning</mark> em projetos ad hoc, aplicando técnicas estatísticas para resolver problemas complexos.

          Criei dashboards interativos para <mark>storytelling</mark>, apresentando informações de maneira atraente e intuitiva. Explorei grandes volumes de dados com <mark>BigQuery</mark>, gerando insights relevantes para a tomada de decisão.

          Desenvolvi soluções tecnológicas para automatizar processos e aumentar a produtividade das áreas de negócio. Também colaborei em estudos setoriais e representei a instituição em reuniões e eventos, comunicando questões técnicas de forma acessível a diferentes partes interessadas.
        
      - layout: left
        border: weak
        title: FGV EPGE
        link: https://epge.fgv.br/pt
        link_text: https://epge.fgv.br/pt
        sub_title: Assistente de Pesquisa
        caption: Dez. 2017 - Abril. 2019
        description: | 
          Atuei em projetos de pesquisa em micro e macroeconomia, com foco na análise econométrica dos efeitos fiscais dos royalties do petróleo sobre o gasto público e o bem-estar municipal. Realizei coleta e tratamento de microdados (RAIS, ANP, FINBRA, entre outros) e estimativas de modelos com dados em painel (efeitos fixos), utilizando R, Stata e Excel.
      
      - layout: left
        # border: weak
        title: SulAmérica
        link: https://portal.sulamericaseguros.com.br/home.htm
        link_text: https://portal.sulamericaseguros.com.br/home.htm
        sub_title: Estágio
        caption: Mar. 2013 - Dez. 2014
        description: | 
          Apoiei na análise de dados financeiros e no gerenciamento de fluxo de caixa, contribuindo para a eficiência das operações.

  - title: Palestras e Atividades Acadêmicas
    layout: list
    content:

      - layout: left
        border: weak
        title: 4ª Semana Estadual do Planejamento, Orçamento e Gestão (SEPOG-PB)
        link: https://paraiba.pb.gov.br/diretas/secretaria-de-planejamento-orcamento-e-gestao/noticias/sepog-traz-painel-sobre-aprimoramento-de-politicas-publicas-com-o-uso-da-ia
        link_text: Matéria oficial da SEPOG-PB
        sub_title: Palestrante Convidado
        caption: Outubro 2025 | João Pessoa (PB)
        description: |
          Atuei como palestrante convidado no painel **“Aprimoramento das Políticas Públicas com o uso de Inteligência Artificial”**, representando a Macroplan Consultoria e Analytics. 
          Durante a palestra (3h de duração), destaquei como a IA pode apoiar políticas públicas quando aliada a:
            - Dados de qualidade; 
            - Adaptação ao contexto local; 
            - Capacitação de servidores.
          
          O evento reuniu gestores públicos e especialistas em inovação governamental para discutir ética, transparência e proteção de dados no uso de IA.  
          Foi uma excelente oportunidade de trocar experiências e contribuir para o avanço da transformação digital no setor público.

      - layout: left
        border: weak
        title: Instituto Nacional de Matemática Pura e Aplicada (IMPA)
        sub_title: Apresentação de Dissertação – Conferência *Research in Options*
        caption: Novembro 2017 | Rio de Janeiro (RJ)
        description: |
          Apresentei minha dissertação de mestrado sobre **modelos estocásticos aplicados a finanças**, destacando a relevância da variável “conveniência” na precificação de commodities no contexto da financeirização.

  - title: Educação 
    layout: list 
    content:
      - layout: left
        border: weak
        title: Instituto Infnet
        caption: 2022 - 2023
        sub_title: Pós Graduação em Inteligência Artificial, Machine Learning e Deep Learning
        description: | 
          Durante o curso, desenvolvi uma série de projetos práticos, incluindo algoritmos supervisionados para classificação, engenharia de Machine Learning e processamento de linguagem natural com Python. Também trabalhei em mineração de texto utilizando Stack Elk e desenvolvi redes neurais e modelos de Deep Learning com Tensorflow.

          Outros projetos envolveram a aplicação de algoritmos não-supervisionados para clusterização e a validação desses modelos. Utilizei diversas ferramentas e tecnologias, como Python, Tensorflow, Jupyter, Elastic Search, Pandas, NLP, Scikit-Learn, redes neurais, AutoML, Dash, SVM, Plot.ly, MLflow e Kedro. 

      - layout: left
        border: weak
        title: UERJ
        caption: 2016 - 2017
        sub_title: Mestrado em Economia Aplicada
        description: | 
          Durante meu mestrado em Economia Aplicada, com ênfase em Finanças Quantitativas e Análise de Risco, adquiri uma sólida formação em modelagem financeira e análise de séries temporais, utilizando o software R. Através de minhas publicações, aprofundei-me na aplicação de modelos estocásticos para a análise de risco e estratégias de hedging, além de explorar a relevância de diferentes variáveis financeiras, como a taxa de juros e a volatilidade, para a previsão de preços e a gestão de portfólios.
      - layout: left
        title: UERJ
        caption: 2010 - 2014
        sub_title: Bacharelado em Ciências Econômicas
        description: | 
          Durante minha graduação, desenvolvi uma base sólida em análise econômica utilizando ferramentas matemáticas e estatísticas. Aprofundei-me em modelos econométricos, técnicas de análise de dados e tópicos como cálculo diferencial e otimização, além de explorar os conceitos centrais de economia monetária, como políticas monetárias, inflação e taxa de juros, o que me permitiu aplicar esses conceitos na resolução de problemas econômicos complexos. Além disso, tive a oportunidade de trabalhar com softwares de análise estatística, como R, Stata e Excel.
  
  - title: Certificações
    layout: text
    content: |
      
      <div id="nomeAnimado" style="font-size: 2em; animation: moverNome 5s infinite;">
        <strong>Inteligência Artificial e Machine Learning</strong>
        </div>

        <style>
        @keyframes moverNome {
            0% { transform: translateX(0); }
            50% { transform: translateX(100px); }
            100% { transform: translateX(0); }
        }
        </style>
        
        - Machine Learning em <mark>Python</mark> e <mark>C++</mark> (Data Science Academy)
        - Machine Learning com <mark>R</mark> (Curso-R)
        - Deploy com Google <mark>Cloud Platform</mark> e <mark>Django</mark> (Data Science Academy)            
        - Machine Learning in R: Classification (DataCamp)
        - Machine Learning in R: Regression (DataCamp)
        - Unsupervised Learning in Python (DataCamp)
        - Natural Language Processing in Python (DataCamp)
        - Inteligência Artificial Generativa (Enap)        
        
       
      <div id="nomeAnimado" style="font-size: 2em; animation: moverNome 5s infinite;">
        <strong>Engenharia de Dados</strong>
        </div>      
          
        <style>
        
        @keyframes moverNome {
            0% { transform: translateX(0); }
            50% { transform: translateX(100px); }
            100% { transform: translateX(0); }
        }
        
        </style>
        
        - Sistema Operacional <mark>Linux</mark>, <mark>Docker</mark> e <mark>Kubernetes</mark> (Data Science Academy)   
        - Introduction to <mark>Apache Airflow</mark> in Python (DataCamp)
        - Analytics em Enterprise <mark>Data Warehouse</mark> com <mark>Google Big Query</mark> (Data Science Academy)
        - Data Warehousing Concepts (DataCamp)
        - Cloud Computing for Everyone (DataCamp)
        
      
      
      <div id="nomeAnimado" style="font-size: 2em; animation: moverNome 5s infinite;">
        <strong>Análise de Dados</strong>
        </div>

        <style>
        @keyframes moverNome {
            0% { transform: translateX(0); }
            50% { transform: translateX(100px); }
            100% { transform: translateX(0); }
        }
        </style>
        - Intermediate SQL Server (DataCamp)
        - Excel Avançado com VBA, Linguagem Python e SQL (Data Science Academy)
        - Foundations of Functional Programming with purrrr (DataCamp)
        - Introduction to Text Analysis in R (DataCamp)
        - String Manipulation with stringr in R (DataCamp)
        - Web Scraping in Python (DataCamp)
        
           
       <div id="nomeAnimado" style="font-size: 2em; animation: moverNome 5s infinite;">
        <strong>Visualização</strong>
        </div>

        <style>
        @keyframes moverNome {
            0% { transform: translateX(0); }
            50% { transform: translateX(100px); }
            100% { transform: translateX(0); }
        }
        </style>
        - <mark>Power BI</mark> para Data Science (Data Science Academy)
        - Dashboards em <mark>Shiny</mark> II (Curso-R)
        - Case Studies: Building Web Applications with <mark>Shiny</mark> in R (DataCamp)
        - Introduction to Tableau (DataCamp)
      
      
      <div id="nomeAnimado" style="font-size: 2em; animation: moverNome 5s infinite;">
        <strong>Governança e Transformação Digital</strong>
        </div>

        <style>
        @keyframes moverNome {
            0% { transform: translateX(0); }
            50% { transform: translateX(100px); }
            100% { transform: translateX(0); }
        }
        </style>
        - Governança de Dados (Data Science Academy)
        - Transformação Digital (FGV)
        - Ética em IA (Enap)
      
        
      <div id="nomeAnimado" style="font-size: 2em; animation: moverNome 5s infinite;">
        <strong>Liderança e Gestão</strong>
        </div>

        <style>
        @keyframes moverNome {
            0% { transform: translateX(0); }
            50% { transform: translateX(100px); }
            100% { transform: translateX(0); }
        }
        </style>
        - Planejamento Estratégico (Enap)
        - Liderança e Gestão de Equipes (Enap)
        - Introdução à Gestão de Projetos (Enap)
        - Soft Skills: Desenvolvendo Suas Habilidades Comportamentais (Data Science Academy)
        - Empreendedorismo em Data Science, IA e Blockchain (Data Science Academy)


  - title: Publicações
    layout: text
    content: |  
      - [Hedging Brazilian equities in the era of low interest rates: What has changed?](https://periodicos.fgv.br/rbfin/article/view/81625) (Brazilian Review of Finance)
      - [Can Gaussian factor models of commodity prices capture the financialization phenomenon?](https://www.sciencedirect.com/science/article/abs/pii/S1062940819300117) (The North American Journal of Economics and Finance)
      - [Análise do comportamento da volatilidade da taxa de câmbio euro-dólar](https://www.e-publicacoes.uerj.br/cadest/article/view/27738) (Cadernos do IME - Série Estatística)

  # - title: Um pouco mais sobre mim
    # layout: text
    # content: |
      # Para além de algoritmos e dados, também me interesso por:
      # - Explorar **trilhas** e descobrir novos caminhos em meio à natureza. 
      # - Desafiar limites no **crossfit** e sentir a força do corpo em movimento.
      # - Aproveitar a liberdade de uma boa **pedalada**, deixando a mente fluir enquanto as rodas giram.
      # - Praticar **yoga** e **meditação**, buscando o equilíbrio entre corpo e mente.
      # - Mergulhar em boas **leituras**, onde cada página é uma oportunidade de expandir minha visão de mundo.
      # - [Buscar respostas nas reflexões espirituais, que dão sentido à jornada.](https://medium.com/@wfaquieri)
      

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
